services:
  app:
    build:
      context: ../../..
      dockerfile: .devcontainer/Dockerfile

    command: sleep infinity

    volumes:
      - ../../..:/workspace:cached
      - go-modules:/go/pkg/mod

    networks:
      - football-simulator-net

    depends_on:
      clickhouse:
        condition: service_healthy
      kafka:
        condition: service_healthy
