services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.12.3.21-alpine

    ulimits:
      nofile:
        soft: 262144
        hard: 262144

    networks:
      - internal

    ports:
      - "8123:8123"

    environment:
      CLICKHOUSE_DB: football_simulator
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}

    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - /opt/football/app/infra/clickhouse/init:/docker-entrypoint-initdb.d:ro
      - /opt/football/app/infra/clickhouse/config/prometheus.xml:/etc/clickhouse-server/config.d/prometheus.xml:ro

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.clickhouse == true
      resources:
        limits:
          memory: 4G

    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3
